//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TERP.Forms.PMS {
    
    
    public partial class frmCriteriaSupplierPerformanceMaint {
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblTitle;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnGoBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnGoBack;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnCreateNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnCreateNew;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnUploadNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnUploadNew;
        
        /// <summary>
        /// fieldSet_Filter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label fieldSet_Filter;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblCode;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_txtCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox frmCriteriaSupplierPerformanceMaint_txtCode;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblStatus;
        
        /// <summary>
        /// ddStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddStatus;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblCategory;
        
        /// <summary>
        /// ddCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddCategory;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblContent;
        
        /// <summary>
        /// ddContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddContent;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblContentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblContentDetail;
        
        /// <summary>
        /// ddContentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddContentDetail;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_filterBtnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_filterBtnSearch;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_filterBtnClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_filterBtnClear;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblRecordPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblRecordPage;
        
        /// <summary>
        /// ddRecordPerPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddRecordPerPage;
        
        /// <summary>
        /// grCriteriaSupplierPerformanceMaint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView grCriteriaSupplierPerformanceMaint;
        
        /// <summary>
        /// fieldSet_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label fieldSet_Form;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblCode;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formtxtCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox frmCriteriaSupplierPerformanceMaint_formtxtCode;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblStatus;
        
        /// <summary>
        /// ddFormStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddFormStatus;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblName;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formtxtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox frmCriteriaSupplierPerformanceMaint_formtxtName;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblContent;
        
        /// <summary>
        /// ddFormContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddFormContent;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblCategory;
        
        /// <summary>
        /// ddFormCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddFormCategory;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblContentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblContentDetail;
        
        /// <summary>
        /// ddFormContentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddFormContentDetail;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblPoints control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblPoints;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formtxtPoints control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox frmCriteriaSupplierPerformanceMaint_formtxtPoints;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formlblOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_formlblOrder;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_formtxtOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox frmCriteriaSupplierPerformanceMaint_formtxtOrder;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnSave;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnCancel;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblDesc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblDesc;
        
        /// <summary>
        /// fileUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblNote;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_lblComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label frmCriteriaSupplierPerformanceMaint_lblComment;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_link control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_link;
        
        /// <summary>
        /// frmCriteriaSupplierPerformanceMaint_btnImport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button frmCriteriaSupplierPerformanceMaint_btnImport;
        
        /// <summary>
        /// dsPOApproval control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource dsPOApproval;
        
        /// <summary>
        /// dsRowPerPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource dsRowPerPage;
    }
}
